### ISSUE TITLE
Update author in setup.py

### ISSUE THREAD

**Issue by Ichimonji10** [pulp/pulp-smash#1224]
# Creating Pulp Smash issues

1. Describe what you expected to happen.

`setup.py` should list contact information for someone currently involved in the project.

2. Describe what actually happened.

`setup.py` lists the following:

```python
    author="Jeremy Audet",
    author_email="ichimonji10@gmail.com",
```

3. Describe what version of Pulp Smash and what OS is affected by the issue.

The master branch (`VERSION` is `1!0.7.0`) is affected.

4. State steps to re-create the issue.

`grep author setup.py`, and examine output.

5. Choose proper labels. See: [Smash Labels](https://pulp-smash.readthedocs.io/en/latest/about.html#labels)

No can do. I don't have permissions for that.

# Creating Pulp issues

1. Issues related to Pulp 2 should be created on [Pulp 2 Tests](https://github.com/PulpQE/Pulp-2-Tests)

2. Issues related to Pulp 3 should be created on [pulp.plan.io](https://pulp.plan.io/). Choose the tags `Pulp 3` and `Functional test`.

**Comment by lubosmj** [comment]
Already resolved by https://github.com/pulp/pulp-smash/commit/a9c3bc7fc4de0e407eb3437ed001c4757a9e6db2.
